application: bdq-pibot
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.APPLICATION

inbound_services:
- xmpp_message

libraries:
- name: jinja2
  version: latest
