import random

def get_random_quote():
	author_index = random.randint(0, len(FUTURAMA_QUOTES)-1)
	author = FUTURAMA_QUOTES.keys()[author_index]
	quotes_from_author = FUTURAMA_QUOTES.values()[author_index]
	quote_index = random.randint(0, len(quotes_from_author)-1)
	return "[" + author + "] " + quotes_from_author[quote_index]

FUTURAMA_QUOTES = {
	"Bender" : [
		"Bite my shiny metal ass!",
		"This is the worst kind of discrimination. The kind against me!",
		"Oh. Your. God.",
		"My life, and by extension everyone else's is meaningless.",
		"I'm Bender, baby, please insert liquor!",
		"They're not very heavy, but you don't hear me not complaining.",
		"Everybody's a jerk. You, me, this jerk.",
		"I hate the people that love me and they hate me.",
		"Do I preach to you while you're lying stoned in the gutter? No.",
		"Tempers are wearing thin. Let's hope some robot doesn't kill everybody.",
		"Bite my shiny metal ass!",
		"I'm gonna go build my own theme park! With blackjack and hookers! In fact, forget the park!",
		"That's no alien spaceship-that's my ass!",
		"Bribe is such an ugly word. I prefer extortion. The X makes it sound cool.",
		"Life can be hilariously cruel.",
		"Leela cracked corn, and i dont care. Fry cracked corn, i still dont care. Bender cracked corn, and he is great! Take that you stupid corn!",
		"Fry, as you know, there are lots of things I'm willing to kill for: jewels, vengeance, Father O'Mallee's weed-whacker. But at long last I've found something I'm willing to die for... This mindless turtle.",
		"Let's face it, comedy's a dead art form. Tragedy, now that's funny.",
		"Great is OK, but amazing would be GREAT.",
		"Congratulations Fry, you've snagged the perfect girlfriend. Amy's rich, she's probably got other characteristics...",
		"Who are you, and why should I care?",
		"What kind of party is this? There's no booze and only one hooker.",
		"I was thinking Benderbrau if it's an ale, Botweiser if it's a lager.",
		"Ahhh, what an awful dream. Ones and zeroes everywhere... and I thought I saw a two.",
		"What do you mean 'we', flesh-tube?",
		"I guess a robot would have to be crazy to wanna' be a folk-singer...",
		"You may need to metaphorically make a deal with the devil. By 'devil' I mean robot devil and by 'metaphorically' I mean get your coat."
	],
	"Fry" : [
		"I'll be whatever I wanna do.",
		"But existing is basically all I do!",
		"Valentine's Day's coming? Aw crap! I forgot to get a girlfriend again!",
		"It's just like the story of the grasshopper and the octopus. All year long, the grasshopper kept burying acorns for winter, while the octopus mooched off his girlfriend and watched TV. But then the winter came, and the grasshopper died, and the octopus ate all his acorns and also he got a racecar. Is any of this getting through to you?",
		"Good 'ol Coney Island College. Go Whitefish!",
		"My folks were always on me to groom myself and wear underpants. What am I, the pope?",
		"Now that's what I call a thousand years of progress: a Bavarian Cream dog that's self-microwaving!",
		"I'm doing my job - there's Amy. I spend a few hours selecting a candy from the machine - there's Amy. I wake up the morning after sleeping with Amy - there's Amy!",
		"I always thought it was real like pro wrestling but it's fixed like boxing.",
		"I'm experienced with foraging. I used to find edible mushrooms on my bath mat!",
		"Poor Bender, you're seeing things. You've been drinking too much. Or too little. I forget how it works with you. Anyway, you haven't drunk exactly the right amount.",
		"Words. Nothing but sweet, sweet words that turn into bitter orange wax in my ears.",
		"All right, all right, if it will make you happy, I will overthrow society.",
		"Goodbye, friends. I never thought I'd die like this. But I always really, really hoped.",
		"Professor, I've never seen you so cheerful. What the hell's wrong with you?",
		"Space, it seems to go on and on forever. But then you get to the end and a gorilla starts throwing barrels at you.",
		"It's the future! My parents, my coworkers, my girlfriend. I'll never see any of them again! Yahooo!"
	],
	"Leela" : [
		"You buy one pound of underwear and you're on their list forever.",
		"At the risk of sounding negative, no.",
		"Alright, This is the third hose fight I've broken up today, and the second using actual hoses.",
		"Look Fry, you're a man and I'm a woman. We're just too different."
	],
	"Professor Farnsworth" : [
		"Everyone's always in favour of saving Hitler's brain. But when you put it in the body of a great white shark, ooohh! Suddenly you've gone too far!",
		"Yes, it's a perfect scale model of the universe's largest bottle. I put a tiny spaceship inside to keep it from being boring.",
		"Good news, everyone! The University is bringing me up on disciplinary charges... wait... that's not good news at all.",
		"Goodbye, cruel world. Goodbye, cruel lamp. Goodbye, cruel velvet drapes, lined with what would appear to be some kind of cruel muslin. And the cute little pom-pom pull ropes, cruel though they may be...",
		"Listen to me, you pompous frauds! If I'm going down, I'm taking you all with me. Dean Vernon, I know the truth. It was you driving your hovercar last night, not your horse! Dean Epsilon, I know all about your Department of Pool Boy Studies. And Doctor Wernstrom... Wernstrom!",
		"53? Oh, now I'll need a fake ID to buy ultra-porn.",
		"With my last breath, I curse Zoidberg!",
		"At this rate, we'll keep getting younger until we suffer a fate worse than death: pre-life! Then death.",
		"You mustn't interfere with the past. Don't do anything that affects anything. Unless it turns out that you were supposed to do it; in which case, for the love of God, don't not do it!",
		"Yes, sir, we tore the universe a new space hole. But it's clenching shut fast.",
		"All this knowledge is giving me a raging brainer!",
		"Hmm. Will said skills pay the bills?",
		"And none too soon. While you were gone, the Trotters held a news conference to announce that I was a jive sucka.",
		"And now I want to shout our love from the rooftops. Perhaps I'll breed some sort of albino shouting gorilla...",
		"Now, now. There'll be plenty of time to discuss your objections when and if you return.",
		"Remarkable. A stench so foul it's right off the funkometer. I dare say, Fry may have discovered the smelliest object in the known universe.",
		"Oh, I always feared he would run off like this. Why? WHY? WHY didn't I break his legs?",
		"What? After I spent MONTHS slaving over a hot monkey brain?",
		"All he handed in was a paper smeared with feces. He tied with Fry.",
		"Oh, dear, I should have shown him 'Electrogonorrhea: the noisy killer' instead.",
		"Oh dear, she's stuck in an infinite loop and he's an idiot! Oh well, that's love for you, I guess.",
		"This is uncomfortable and humiliating. Now if they were to make it in the form of a suppository...",
		"I have made the modifications on the ships engines. We'll be able to leave as soon as the papier-mache is dry.",
		"I can wire anything directly into anything! I am the Professor!",
		"I'm sciencing as fast as I can!",
		"Remember, we need to show these people that we are not bitter husks of human beings, who long ago abandoned hope of finding love in this lifetime. Leela, you'll have to do some acting.",
		"Buddha! Zeus! God! One of you guys help me! Satan, you owe me!",
		"Oh, dear. I really ought to do something. But I am already in my pajamas.",
		"Most video tapes from that era were damaged in 2443, during the second coming of Jesus.",
		"Good news everyone, I've taught the toaster to feel love.",
		"Oh how awful. Did he at least die peacefully? To shreds you say? Tsk tsk tsk. Well, how's his wife holding up? To shreds, you say?",
		"We're certainly not building anything sinster, if that's what you mean. Come on, Bender. Something sinister won't build itself."
	],
	"Zapp Brannigan" : [
		"I've never heard of such a brutal and shocking injustice that I cared so little about.",
		"The best way into a girl's bed is through her parents. Have sex with them, and you're in.",
		"If we hit that bullseye, the rest of the dominos will fall like a house of cards. Checkmate.",
		"You win again, gravity!",
		"Kif, I have made it with a woman. Inform the men. ",
		"Brannigan's Law is like Brannigan's love, hard and fast. ",
		"Mmm... Welcome to my humble chamber or as I call it, 'The Lovenasium'.",
		"In the game of chess you can never let your adversary see your pieces.",
		"It was almost the perfect crime, but you forgot the one thing: rock crushes scissors. But paper covers rock. And scissors cut paper! Kif, we have a conundrum. Search them for paper... and bring me a rock.",
		"Now you're officially my woman. Kudos! I can't say I don't envy you.",
		"You'll be negotiating with the balls mysterious leaders, the Brain Balls. They've got a lot of brains, and they've got a lot of chutzpah...",
		"That young man fills me with hope. Plus some other emotions which are weird and deeply confusing.",
		"As you know, the key to victory is the element of surprise... Surprise!",
		"Private Lemon is the finest soldier I've seen since my mirror got grease on it.",
		"We need rest. The spirit is willing, but the flesh is spongy and bruised.",
		"Well, this promises to be one disturbingly erotic date.",
		"You know, I find the most erotic part of a woman is the boobies.",
		"But as a gentleman, I must warn you, if you so much as glance at another woman, I'll be on Leela like a fly on a pile of very seductive manure.",
		"She's a beautiful ship. Shapely, seductive. I'm gonna fly her brains out.",
		"Don't be such a chicken, Kif. Teenagers smoke, and they seem pretty on-the-ball.",
		"I surrender and volunteer myself for treason!",
		"Fire all weapons and set a transmission frequency for my victory yodel."
	],
	"Zoidberg" : [
		"You don't want to end up old and lonely like ZOIDBERG (cries).",
		"It's toe-tappingly tragic.",
		"I finally learned what it's like to be a grandmother; subjugated, yet honored.",
		"I'll just turn the wheel to maximum fastness.",
		"Your music is bad, and you should feel bad!",
		"Yippe ki yay! You'll never guess where I have been!",
		"What you guys up to tonight. Im up for whatever.",
		"I have mail order degrees in murder-ology and murder-ometry.",
		"Friends, help! A guinea pig tricked me!",
		"A buffet.... oh if only i'd brought my wallet with me.",
		"You still have your old pal Zoidberg. YOU ALL HAVE ZOIDBERG.",
		"Ain't Got no cash, ain't got no style, ladies vomit when I smile, but does Zoidberg worry?",
		"I am Zoidberg, home owner!",
		"These night crawlers though juicy, mmm very very juicy, would not be good.",
		"You have no nose on your face. Where it is I can't say, but in your face it is not.",
		"And why did I have to take a cab?",
		"My house! It burned down! How did this happen?!",
		"Your student loans have been repayed? Then how about lending your old pal Zoidberg a few bucks, Mr Millionaire.",
		"Stop! Stop! I admit it! My people ate them all! We kept saying 'One more can't hurt' and then they were gone, we're sorry!"
	]
}